[package]
name = "ncspot-controller"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
notify = "8.2"
clap = { version = "4.5", features = ["derive"] }
toml = "0.9"
shellexpand = "3.1"
ureq = "2.10"
